name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libfuse3-dev fuse3

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
        targets: ${{ matrix.target }}
        cache: 'cargo'
        toolchain: stable
        profile: minimal

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Check
      run: cargo check --verbose

    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Test
      run: cargo test --verbose 